export const POST_LOADING = '@post/loading'
export const POST_INIT = '@post/init'
export const POST_CREATED = '@post/created'
export const POST_FILTERED = '@post/filtered'
export const POST_LOADING_MORE = '@post/loading_more'
export const POST_LOAD_MORE = '@post/load_more'
